# enable 256 colors
#set -g default-terminal "screen-256color"

# enable 256 colors + italic comments in vim
set -g default-terminal "xterm-256color"

# enable copy text to clipboard from buffer with "y" key 
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"

# Set default shell to bash
set-option -g default-shell /bin/zsh
set-option -g default-command /bin/zsh

#
set-option -g base-index 1
set-option -g pane-base-index 1

# highlight the current terminal
# set -g window-status-current-style 'bg=colour097 fg=colour129'
# move around copy/paste with vi
set -g mode-keys vi
# setup status bar (dark aqua bg, light gray text, with clock)
#set -g status-bg colour60
#set -g status-fg colour248
set -g status-right "%a %b %d %I:%M %p"

# hold on to old screen habit of Ctrl-A for prefix and also last window combo (C-a C-a)
set-option -g prefix C-a
bind-key C-a last-window

## Begin styling the status line here

RED="#f7768e"
ORANGE="#ff9e64"
YELLOW="#e0af68"
GREEN="#9ece6a"
TEAL="#73daca"
CYAN="#7dcfff"
BLUE="#7aa2f7"
PURPLE="#bb9af7"
PINK="#f5c2e7"
WHITE="#c0caf5"
GRAY_DARK="#1a1b26"
GRAY_MED="#2f334d"
GRAY_LIGHT="#565f89"

# Foreground Color for whole session
FG=${GREEN}

# unicode powerline symbols from:
# https://github.com/ryanoasis/powerline-extra-symbols

LEAD_TRIANGLE="#(printf '\uE0BA')"
LEAD_DIGITAL="#(printf '\uE0C7')"
LEFT_CIRCLE="#(printf '\uE0B6')"
RIGHT_CIRCLE="#(printf '\uE0B4')"

set-option -g window-status-separator ""


#set-option -g status-left "#S "
set-option -g status-left ""


set-option -g status-style bg=${GRAY_MED},fg=${FG}

set-option -g status-right "\
#[bg=default,fg=${FG}]${LEAD_TRIANGLE}\
#[bg=${FG},fg=${GRAY_MED}] #h "

set-option -g window-status-format " #I:#W "

set-option -g window-status-current-format "\
#[bg=default,fg=${FG}]${LEFT_CIRCLE}\
#[fg=${GRAY_MED},bg=${FG}]#I:#W\
#[bg=default,fg=${FG}]${RIGHT_CIRCLE}\
"

